# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  clean_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clone Lab2---Obr-bka-danych repository
        run: git clone https://github.com/PJATK-ASI-2024/Lab2---Obr-bka-danych.git

      - name: Change directory to Lab2 repo
        run: cd Lab2---Obr-bka-danych

      - name: Install Lab2 dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data generation
        run: python3 generator_danych.py -s 24661

      - name: Run the data processing script
        run: |
          cd ..
          python s24661.py  

      - name: Show the report
        run: cat raport.txt

      - name: Show the logs
        run: cat log.txt
