# .github/workflows/ci.yml

name: CI/CD Pipeline for Data Analysis

on:
  workflow_dispatch:

jobs:
  data_analyzer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the data analyzer
        run: python analyzer.py  

      - name: Show the results of analysis
        run: cat data_info.txt

      - name: Run the data predictor
        run: python predicter.py 

      - name: Show the results of data preparation
        run: cat preparation_result.txt

      - name: Show the results of training
        run: cat train_result.txt
